version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: lynnapse-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: lynnapse
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - lynnapse-network

  lynnapse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lynnapse-app
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGODB_URL: mongodb://admin:password@mongodb:27017/lynnapse?authSource=admin
      MONGODB_DATABASE: lynnapse
      PLAYWRIGHT_HEADLESS: "true"
      LOG_LEVEL: INFO
    volumes:
      - ./seeds:/app/seeds:ro
      - ./output:/app/output
      - ./logs:/app/logs
    networks:
      - lynnapse-network
    command: python -m lynnapse.cli scrape "University of Arizona" --verbose

  mongo-express:
    image: mongo-express:latest
    container_name: lynnapse-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - lynnapse-network

volumes:
  mongodb_data:

networks:
  lynnapse-network:
    driver: bridge 