version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: lynnapse-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: lynnapse
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - lynnapse-network

  lynnapse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lynnapse-app
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/lynnapse?authSource=admin
      - LYNNAPSE_ENV=docker
      - PLAYWRIGHT_HEADLESS=true
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./data:/app/data
      - ./seeds:/app/seeds
    networks:
      - lynnapse-network
    # Keep container running for manual commands
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  mongo-express:
    image: mongo-express
    container_name: lynnapse-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - lynnapse-network

volumes:
  mongodb_data:
    driver: local

networks:
  lynnapse-network:
    driver: bridge 